### ISSUE TITLE
Main website (xbarapp.com) down (Server Error)

### ISSUE THREAD

**Issue by mmuman** [matryer/xbar-plugins#1867] opened 2022-10-16 19:22 UTC
I noticed that xbarapp.com gives a Server Error currently, didn't know how to reach the maintainer…

**Comment by sprak3000** [comment] 2023-03-22 01:39
Site is up and running. This may have been caused by a site deploy or other error in the past. Closing.

**Closed by sprak3000** 2023-03-22 01:39 UTC
