### ISSUE TITLE
Watt Meter: KeyError: 'sppower_current_amperage'

### ISSUE THREAD

**Issue by ssbarnea** [matryer/xbar-plugins#1176] opened 2019-02-06 10:53 UTC
imac:~ ssbarnea$ /Users/ssbarnea/Library/Mobile\ Documents/com~apple~CloudDocs/configs/bitbar/watt-meter.20s.py
Traceback (most recent call last):
  File "/Users/ssbarnea/Library/Mobile Documents/com~apple~CloudDocs/configs/bitbar/watt-meter.20s.py", line 78, in <module>
    main()
  File "/Users/ssbarnea/Library/Mobile Documents/com~apple~CloudDocs/configs/bitbar/watt-meter.20s.py", line 65, in main
    machine = parse_system_profiler()
  File "/Users/ssbarnea/Library/Mobile Documents/com~apple~CloudDocs/configs/bitbar/watt-meter.20s.py", line 43, in parse_system_profiler
    "current_amperage": int(spbattery_info['sppower_current_amperage']),
KeyError: 'sppower_current_amperage'
imac:~ ssbarnea$ 

FAO: (@eripa)

**Comment by capitolmatt22** [comment] 2022-04-12 02:41
Also getting this issue on a 2019 MacBook pro with Monteray

**Comment by gingerbeardman** [comment] 2022-09-17 13:12
closing as dupe of #1176

**Comment by gingerbeardman** [comment] 2022-09-17 13:13
@eripa this plugin no longer works on the latest macOS, where output format of system profiler has changed and Apple silicon CPUs are reported in a different way.

Details at: matryer/xbar#849

**Closed** 2022-10-22 08:56 UTC
