### ISSUE TITLE
Watt Meter(by Eric Ripa) Issue Mackbook Air M1

### ISSUE THREAD

**Issue by moeezulhassan** [matryer/xbar-plugins#1819] opened 2022-04-26 00:39 UTC
fork/exec ./001-watt-meter.5s.py: no such file or directory.

**Comment by xe-nvdk** [comment] 2022-07-21 16:45
Hey, how're you? Please, if you installed python using homebrew, please, in the first line of script, put the following line:

`#!/opt/homebrew/bin/python3`

Let me know if that worked.

**Comment by gingerbeardman** [comment] 2022-09-17 13:12
closing as dupe of #1176

**Closed by gingerbeardman** 2022-09-17 13:12 UTC

**Comment by hy4015** [comment] 2023-07-07 02:06
> Hey, how're you? Please, if you installed python using homebrew, please, in the first line of script, put the following line:
> 
> `#!/opt/homebrew/bin/python3`
> 
> Let me know if that worked.

Didn't work:
exit status T: Traceback (most recent call last):
File "/Users/thhe/Library/Application Support/xbar/plugins/./001-bilibili.py", line 28, in <module>
for video in sub MitVideosResL"data"jrnvlist']:
~     AAAAAAAAA
TypeError: string indices must be integers, not 'str'
