### ISSUE TITLE
001-cpu-temperature.5s.sh: 

### ISSUE THREAD

**Issue by leland359** [matryer/xbar-plugins#1684] opened 2021-09-03 02:18 UTC
fao @eripa - where do I find the external 'smc' binary that the description says is needed for the CPU Temperature Plugin?

**Comment by ksakiyama** [comment] 2021-09-09 15:03
duplicate of https://github.com/matryer/xbar-plugins/issues/434

**Closed** 2023-03-22 02:28 UTC
