### ISSUE TITLE
001-watt-meter.20s.py: 

### ISSUE THREAD

**Issue by capitolmatt22** [matryer/xbar-plugins#1814] opened 2022-04-12 02:45 UTC
fao @eripa - 

Getting `KeyError: sppower_current_amperage` on a 2019 MacBook Pro running Monteray. Duplicate of https://github.com/matryer/xbar-plugins/issues/1176

**Comment by gingerbeardman** [comment] 2022-09-17 13:12
closing as dupe of #1176

**Closed by gingerbeardman** 2022-09-17 13:12 UTC
